### PR TITLE
Build cleanup

### PR DESCRIPTION
**Pull request by hackermd**
I cleaned up the `CMakeLists.txt` files to ensure that the native C library, the C example, and the wasm bindings can be build successfully.

I still don't like that we keep a full copy of the lcms2 library in the repo. @Punzo can we not include it as a git submodule instead?

### CODE REVIEW

**Comment by Punzo** [comment]
I am not sure you can use git submodule for a non CMake project as lcms2. Moreover, I really dislike git submodule for several reasons (but I will not rant about it here now (: ).  

if lcms2 was a CMake project, I would have used CMake fetch (https://cmake.org/cmake/help/latest/module/FetchContent.html) and then compiled in this repo.

Therefore, I think teh best is to use ExternalProject_Add https://cmake.org/cmake/help/latest/module/ExternalProject.html. However lcms2 is not a CMake  project. So you need to specify the configure, build and install commands manually. Something like this:

```
include(ExternalProject)
ExternalProject_Add(lcms2
  GIT_REPOSITORY    https://github.com/mm2/Little-CMS
  GIT_TAG           master
  SOURCE_DIR        "${CMAKE_BINARY_DIR}/lcms2-src"
  BINARY_DIR        "${CMAKE_BINARY_DIR}/lcms2-build"
  CONFIGURE_COMMAND configure ....etc...
  BUILD_COMMAND     make
  INSTALL_COMMAND   ""
  TEST_COMMAND      ""
)
```

**Comment by Punzo** [comment]
@hackermd 
in general I think the easiest way is to make lcms2 a cmake project and then use FetchContent. However we would need to submit a PR to the lcms2 repo.

**Comment by hackermd** [comment]
I am also not a fan of git modules in general. However, I would like to preserve the git history of the original repo. In addition, the C library doesn't need the lcms2 source code and I updated the build files to find and use the lcms2 library installed on the system instead.

Can't we keep the `CMakeLists.txt` files in the repo (maybe move them a little bit) next to the git module dir?

We could also use git subtree instead of git submodule. However, for this repo I would prefer git submodule, because for folks just using working with the native library (without the WASM bindings), the lcms2 source code is not needed and the submodule checkout can be skipped.

**Comment by hackermd** [comment]
@Punzo I have pushed a first pre-release version of the package to the npm registry: https://www.npmjs.com/package/dicomicc/v/0.1.0-0

Once you finalize the `ExternalProject_Add` part, we can merge this PR into master and release version `v0.1.0`.

**Comment by Punzo** [comment]
> @Punzo I have pushed a first pre-release version of the package to the npm registry: https://www.npmjs.com/package/dicomicc/v/0.1.0-0
> 
> Once you finalize the `ExternalProject_Add` part, we can merge this PR into master and release version `v0.1.0`.

@hackermd  done in https://github.com/hackermd/libdicomicc/pull/4/commits/649faa933aac01a72d5d8a3833fb84ff75f3e722. 

if lcms2 will change into a CMake project, the repo could be further cleaned by using a "SuperBuild".

**Comment by hackermd** [comment]
@Punzo the build process fails on my Mac with the following error:

```none
[ 38%] Performing configure step for 'lcms2'
checking build system type... Invalid configuration `arm64-apple-darwin21.3.0': machine `arm64-apple' not recognized
configure: error: /bin/sh ./config.sub arm64-apple-darwin21.3.0 failed
make[2]: *** [lcms2-prefix/src/lcms2-stamp/lcms2-configure] Error 1
make[1]: *** [CMakeFiles/lcms2.dir/all] Error 2
make: *** [all] Error 2
emmake: error: 'make' failed (returned 2)
```

**Comment by hackermd** [comment]
The `ExternalProject_Add` seems to fetch the source code and then just run `configure`. Shouldn't we fetch the tarball instead of the source code?

**Comment by hackermd** [comment]
Or we really build from source using `autogen.sh`. However, we I try this, I get the following error:

```none
[ 23%] Performing configure step for 'lcms2'

**Error**: You must have libtool installed.
You can get it from: ftp://ftp.gnu.org/pub/gnu/
make[2]: *** [lcms2-prefix/src/lcms2-stamp/lcms2-configure] Error 1
make[1]: *** [CMakeFiles/lcms2.dir/all] Error 2
make: *** [all] Error 2
emmake: error: 'make' failed (returned 2)
```

CMake doesn't find libtool (it is installed on the system).

**Comment by Punzo** [comment]
> The `ExternalProject_Add` seems to fetch the source code and then just run `configure`. Shouldn't we fetch the tarball instead of the source code?

usually not. However I agree with you in this case, since the source code is 70 MB just for pdf. I have updated the building in https://github.com/hackermd/libdicomicc/pull/5

**Comment by Punzo** [comment]
> Or we really build from source using `autogen.sh`. However, when I try this, I get the following error:
> 
> ```
> [ 23%] Performing configure step for 'lcms2'
> 
> **Error**: You must have libtool installed.
> You can get it from: ftp://ftp.gnu.org/pub/gnu/
> make[2]: *** [lcms2-prefix/src/lcms2-stamp/lcms2-configure] Error 1
> make[1]: *** [CMakeFiles/lcms2.dir/all] Error 2
> make: *** [all] Error 2
> emmake: error: 'make' failed (returned 2)
> ```
> 
> CMake doesn't find libtool (it is installed on the system).

I can't reproduce, I am not sure how to fix it, sorry. Also I think cmake here does not play any role. It simply run a command on the terminal. Can you try if you can compile separately  lcms2 from a clean source?

**Comment by hackermd** [comment]
> I can't reproduce, I am not sure how to fix it, sorry. Also I think cmake here does not play any role. It simply run a command on the terminal. Can you try if you can compile separately lcms2 from a clean source?

You are right, it had nothing to do with CMake. The `autogen.sh` does seem to take mac OSX specifics into account and therefore cannot find libtool. Using `autoreconf -fvi` instead appears to work..

**Comment by hackermd** [comment]
I'll create a separate PR and include a GitHub workflow to test the building on different operating systems. It would be great if you could also try it on your end.

**Comment by Punzo** [comment]
> I'll create a separate PR and include a GitHub workflow to test the building on different operating systems. It would be great if you could also try it on your end.

done tested, works on my linux and I have update https://github.com/hackermd/libdicomicc/pull/5

**Pull request merged**
